CREATE DATABASE IF NOT EXIST 'ImageDB';

USE ImageDB;

CREATE DATABASE ImageDB;

USE ImageDB;

CREATE TABLE image (
    id INT AUTO_INCREMENT PRIMARY KEY,
    image_url VARCHAR(255) NOT NULL,
    keyword VARCHAR(100) NOT NULL,
    date_uploaded TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
